name: kanza_di
description: "Simple Dependency Injector based on InheritedWidget"
version: 1.0.0
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  kanza_lints: ^1.0.0
